config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'
  devise_for :users, controllers: { registrations: "registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # possibly needed for ActionCable
   mount ActionCable.server => '/cable'

resources :users
resources :messages

  resources :postings, only: [:index, :show] do
    resources :comments, only: [:index]
  end

  namespace :api do
    namespace :v1 do
      resources :messages, only: [:create, :index]
      resources :users, only: [:show]
      get "users/current" => "users#current_user"
    end
  end


  namespace :api do
    namespace :v1 do
        resources :postings, only: [:index, :new, :create, :show] do
          resources :comments, only: [:index, :new, :create, :show]
        end
      end
    end

  namespace :api do
      namespace :v1 do
          resources :users, only: [:show, :new, :create] do
              resources :postings, only: [:index, :new, :create, :show]
          end
        end
      end
  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chat.rb
class Chat < ApplicationRecord
  has_many :messages

end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :description, presence: true

  belongs_to :user
  belongs_to :posting
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :chat
  belongs_to :user


end

app/models/posting.rb
class Posting < ApplicationRecord
  validates :description, presence: true

  belongs_to :user
  has_many :comments
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :postings
  has_many :comments
  has_many :messages

  geocoded_by :location
  after_validation :geocode, :if => :location_changed?
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController
protect_from_forgery unless: -> { request.format.json? }
  before_action :authorize_user

 def index
   render json: Comment.all.order(created_at: :desc)
 end

  def show
    render json: Comment.find(params[:id])
  end

def create
  new_comment = Comment.new(comments_params)
  new_comment.user = current_user
  new_comment.posting_id = params["posting_id"]
  if new_comment.save
    render json: new_comment
  else
    render json: {error: new_comment.errors.full_messages}
  end
end

private

def comments_params
  params.permit(:description)
end

def authorize_user
    if !user_signed_in?
      render json: {message: "You must be signed in to post."}
    end
  end
end

app/controllers/api/v1/messages_controller.rb
class Api::V1::MessagesController < Api::ApiController

end

# DEFUNCT CODE FROM ANOTHER AGE

def create
  if params[:message].present?
    ActionCable.server.broadcast "chat_channel", message: params[:message], handle: current_user.handle, icon_num: assign_icon_num, key: "#{Time.now.to_datetime.strftime('%Q')}-#{current_user.id}"
    render json: { message: params[:message], handle: current_user.handle }, status: :accepted
  else
    render json: { errors: "bad request" }, status: :bad_request
  end
end
private

def assign_icon_num
  if current_user.icon_num.nil?
    rando = rand(1..4)
    current_user.update(icon_num: rando)
  else
    current_user.icon_num
  end
end

app/controllers/api/v1/postings_controller.rb
class Api::V1::PostingsController < ApplicationController
protect_from_forgery unless: -> { request.format.json? }
  before_action :authorize_user

def index
  render json: Posting.all.order(created_at: :desc)
end

def show
  render json: Posting.find(params[:id])
end

def new
  new_postings = Posting.new
end

def create
  new_postings = Posting.new(postings_params)
  new_postings.user = current_user
  if new_postings.save
    render json: new_postings
  else
    render json: {error: new_postings.errors.full_messages}
  end
end


private

  def postings_params
    params.permit(:description)
  end

def authorize_user
    if !user_signed_in?
      render json: {message: "You must be signed in to post."}
    end
  end

  def current_user_access
    current_user.id == Posting.find(params[:id]).user_id
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController

  def show
    render json: { user_id: current_user.id, name: current_user.name  }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  def after_sign_in_path_for(resource) "/postings" end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    
  end
end

app/controllers/postings_controller.rb
class PostingsController < ApplicationController

  def show 
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  protected

  def after_sign_up_path_for(resource) "/postings" end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  protect_from_forgery unless: -> { request.format.json? }
  before_action :authorize_user

  def show
    @user = User.find(params[:id])
  end



  def edit
    @user = User.find(params[:id])
  end

  def update
  @user = User.find(params[:id])
  if @user.update_attributes(user_params)
    redirect_to user_path
  else
    render :action => 'edit'
  end
end



private

private

  def user_params
    params.require(:user).permit(:name, :bio, :location, :longitude, :latitude, :instruments, :influences, :links, :projects, :music_software)
  end
  def authorize_user
    if !user_signed_in?
      render json: {message: "You must be signed in to post."}
    end
  end
end

app/views/homes/index.html.erb
<div class="app" id="app"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css" integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">

  <div class="cool">

   <body>

  <nav class="top-bar">
    <div class="top-bar-left">
          <h1><a class="title" href="/users/sign_in"><img src="https://i.imgur.com/Wgx8PAL.jpg" alt="logo" width="150" height="100"></a></h1>
    </div>

    <section class="top-bar-right">
      <ul class="menu">
        <%- if current_user -%>
        <li><%= link_to 'Home', postings_path, class: "font" %></li>

        <li><%= link_to current_user.name, user_path(current_user), class: "font" %></li>
        <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, class: "font" %></li>

        <%- else -%>
          <div class="cool"
          <li><%= link_to 'Sign Up', new_user_registration_path, class: "font"%></li>
          </div>

          <li><%= link_to 'Sign In', new_user_session_path, class: "font" %></li>

        <%- end -%>
      </ul>
    </section>
  </nav>



  <%= yield %>

  <%= javascript_include_tag 'application' %>

  <%- if Rails.env.development? || Rails.env.test? -%>
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>

  <%= yield :extra_footer %>
  </body>


</div>
  </html>

app/views/messages/index.html.erb
<div id="app" ></div>

app/views/postings/show.html.erb
<div id="app" ></div>

app/views/users/edit.html.erb
<div class="edit-container">

<%= form_for(@user) do |f| %>
<div class='grid-container'>
  <div class="field">
    <%= f.label :name, class: "font-form" %><br />
    <%= f.text_field :name %>
  </div>
</div>

<div class='grid-container'>
  <div class="field">
    <%= f.label :location, class: "font-form" %><br />
    <%= f.text_field :location %>
  </div>
</div>
<div class='grid-container'>

  <div class="grid-item">
    <%= f.label :instruments, class: "font-form" %><br />
    <%= f.text_field :instruments %>
  </div>

  <div class="grid-item">
    <%= f.label :music_software, class: "font-form" %><br />
    <%= f.text_field :music_software %>
  </div>
</div>

<div class='grid-container'>
  <div class="grid-item">

    <%= f.label :influences,class: "font-form" %><br />
    <%= f.text_field :influences %>
  </div>

  <div class="grid-item">
    <%= f.label :projects, class: "font-form" %><br />
    <%= f.text_field :projects %>
  </div>
</div>

  <div class="field">
    <%= f.label :bio, class: "font-form" %><br />
    <%= f.text_field :bio %>
  </div>



  <div class="actions">
    <%= f.submit "Save", :class => 'submit'  %>
  </div>
<% end %>
</div>

app/views/users/show.html.erb
<div class="everything">
  <div class='grid-container'>
      <div class="grid-item">
  <div class="container">
    <div class="avatar-flip">
      <%= image_tag "#{@user.profile_photo}" %>
        <%= image_tag "#{@user.profile_photo}" %>
    </div>
    <h2><%= @user.name %></h2>
    <p><%= @user.location %></p>
    <p><%= @user.bio %></p>
    <p><%= @user.instruments %></p>
    <p><%= @user.influences %></p>
    <p><%= @user.music_software %></p>


  </div>
  </div>

    <div class="grid-item">
  <div class="links">
    <%- if current_user -%>
  <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@user.latitude},#{@user.longitude}&zoom=12&size=400x400&key=AIzaSyAELaqzLiJNExfkGSHYMc_kAxYpLJpgf9g" %>
    <%= link_to 'Update Profile', edit_user_path, class: 'font-form' %>
      <%- else -%>
      <%= image_tag "https://maps.googleapis.com/maps/api/staticmap?center=#{@user.latitude},#{@user.longitude}&zoom=12&size=#{ENV["GOOGLE_MAPS_API"]}" %>

        <%- end -%>
    </div>

  </div>

</div>